import { Ticket, Employee } from './ticket-types'

export const sampleTickets: Ticket[] = [
  {
    id: 'TKT-001',
    title: 'Password Reset Issue',
    description: 'User unable to reset password on the portal',
    status: 'open',
    priority: 'high',
    department: 'IT Support',
    assignee: 'John Smith',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'TKT-002',
    title: 'Invoice Generation Error',
    description: 'System throwing error when generating invoices for large orders',
    status: 'in-progress',
    priority: 'critical',
    department: 'Finance',
    assignee: 'Sarah Johnson',
    createdAt: new Date('2024-03-24'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-003',
    title: 'Database Connection Timeout',
    description: 'Database connections timing out during peak hours',
    status: 'in-progress',
    priority: 'critical',
    department: 'Infrastructure',
    assignee: 'Michael Chen',
    createdAt: new Date('2024-03-23'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-004',
    title: 'User Profile Update Not Saving',
    description: 'User profile changes not persisting after save button click',
    status: 'on-hold',
    priority: 'medium',
    department: 'Development',
    assignee: 'Emma Davis',
    createdAt: new Date('2024-03-22'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'TKT-005',
    title: 'Email Template Missing Variables',
    description: 'Email notifications missing dynamic variables like customer name',
    status: 'closed',
    priority: 'medium',
    department: 'Development',
    assignee: 'David Wilson',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-24'),
    resolutionNotes: 'Updated email template with correct variable mappings',
  },
  {
    id: 'TKT-006',
    title: 'VPN Access Request',
    description: 'New employee needs VPN access for remote work',
    status: 'open',
    priority: 'high',
    department: 'IT Support',
    assignee: 'John Smith',
    createdAt: new Date('2024-03-26'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-007',
    title: 'Report Generation Slow',
    description: 'Monthly reports taking 30+ minutes to generate',
    status: 'on-hold',
    priority: 'medium',
    department: 'Analytics',
    assignee: 'Lisa Anderson',
    createdAt: new Date('2024-03-21'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'TKT-008',
    title: 'API Rate Limit Issue',
    description: 'External API integration hitting rate limits',
    status: 'in-progress',
    priority: 'high',
    department: 'Infrastructure',
    assignee: 'Michael Chen',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-009',
    title: 'Documentation Outdated',
    description: 'API documentation needs updates for v2.0 changes',
    status: 'closed',
    priority: 'low',
    department: 'Technical Writing',
    assignee: 'Rachel Green',
    createdAt: new Date('2024-03-19'),
    updatedAt: new Date('2024-03-23'),
    resolutionNotes: 'Updated all documentation to reflect latest API version',
  },
  {
    id: 'TKT-010',
    title: 'Mobile App Crash on Login',
    description: 'Mobile app crashes when logging in on Android devices',
    status: 'open',
    priority: 'critical',
    department: 'Mobile Development',
    assignee: 'James Martin',
    createdAt: new Date('2024-03-26'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-011',
    title: 'GDPR Compliance Audit',
    description: 'Quarterly GDPR compliance review and documentation',
    status: 'in-progress',
    priority: 'high',
    department: 'Compliance',
    assignee: 'Patricia Lee',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-26'),
  },
  {
    id: 'TKT-012',
    title: 'Server Migration Preparation',
    description: 'Prepare for migration to new cloud provider',
    status: 'on-hold',
    priority: 'high',
    department: 'Infrastructure',
    assignee: 'Michael Chen',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-25'),
  },
]

export const sampleEmployees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@rayinc.com',
    department: 'Design',
    title: 'Senior UX Designer',
    phone: '+91 98765 43210',
    bio: 'Rajesh has 7 years of UX design experience specializing in user-centered design and interface optimization.',
  },
  {
    id: 'EMP-002',
    name: 'Priya Singh',
    email: 'priya.singh@rayinc.com',
    department: 'Engineering',
    title: 'Backend Engineer',
    phone: '+91 98765 43211',
    bio: 'Priya is a skilled backend engineer with 5 years of experience building scalable APIs and services.',
  },
  {
    id: 'EMP-003',
    name: 'Vikram Patel',
    email: 'vikram.patel@rayinc.com',
    department: 'Finance',
    title: 'Finance Analyst',
    phone: '+91 98765 43212',
    bio: 'Vikram specializes in financial analysis and reporting with expertise in compliance and auditing.',
  },
  {
    id: 'EMP-004',
    name: 'Anjali Sharma',
    email: 'anjali.sharma@rayinc.com',
    department: 'Product',
    title: 'Product Manager',
    phone: '+91 98765 43213',
    bio: 'Anjali leads product strategy with 6 years of experience in agile product development.',
  },
  {
    id: 'EMP-005',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@rayinc.com',
    department: 'Infrastructure',
    title: 'DevOps Engineer',
    phone: '+91 98765 43214',
    bio: 'Arjun manages cloud infrastructure and ensures system reliability with extensive DevOps expertise.',
  },
  {
    id: 'EMP-006',
    name: 'Neha Gupta',
    email: 'neha.gupta@rayinc.com',
    department: 'Engineering',
    title: 'Frontend Developer',
    phone: '+91 98765 43215',
    bio: 'Neha specializes in React development with a focus on modern UI/UX implementation.',
  },
  {
    id: 'EMP-007',
    name: 'Sanjay Verma',
    email: 'sanjay.verma@rayinc.com',
    department: 'Analytics',
    title: 'Data Analyst',
    phone: '+91 98765 43216',
    bio: 'Sanjay transforms business data into actionable insights using advanced analytics tools.',
  },
  {
    id: 'EMP-008',
    name: 'Divya Nair',
    email: 'divya.nair@rayinc.com',
    department: 'Quality Assurance',
    title: 'QA Engineer',
    phone: '+91 98765 43217',
    bio: 'Divya ensures product quality through comprehensive testing and automation frameworks.',
  },
  {
    id: 'EMP-009',
    name: 'Rohit Joshi',
    email: 'rohit.joshi@rayinc.com',
    department: 'Business',
    title: 'Business Analyst',
    phone: '+91 98765 43218',
    bio: 'Rohit bridges business and technology with 5 years of experience in requirements analysis.',
  },
  {
    id: 'EMP-010',
    name: 'Meera Kapoor',
    email: 'meera.kapoor@rayinc.com',
    department: 'Human Resources',
    title: 'HR Manager',
    phone: '+91 98765 43219',
    bio: 'Meera manages human resources with expertise in talent acquisition and employee development.',
  },
  {
    id: 'EMP-011',
    name: 'Aditya Malhotra',
    email: 'aditya.malhotra@rayinc.com',
    department: 'Engineering',
    title: 'Senior Developer',
    phone: '+91 98765 43220',
    bio: 'Aditya is a seasoned developer with 8 years of experience in full-stack development.',
  },
]


// =====================================================================
// Chatbot queries — seeded for dashboard widgets. Real telemetry will
// replace this when the Python backend is wired.
// =====================================================================

import type { ChatbotQuery } from './chatbot-types'

export const sampleChatbotQueries: ChatbotQuery[] = [
  { id: 'Q-0072', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: true, confidence: 0.72, responseTimeMs: 1561, escalatedToTicket: false, askedAt: new Date('2026-05-23T23:44:00.000Z') },
  { id: 'Q-0108', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "How do I connect to the office VPN?", topic: 'vpn', wasResolved: true, confidence: 0.83, responseTimeMs: 4233, escalatedToTicket: false, askedAt: new Date('2026-05-23T21:57:00.000Z') },
  { id: 'Q-0157', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "GitHub access for new repo", topic: 'access', wasResolved: true, confidence: 0.82, responseTimeMs: 2200, escalatedToTicket: false, askedAt: new Date('2026-05-23T21:35:00.000Z') },
  { id: 'Q-0064', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Dental coverage included?", topic: 'benefits', wasResolved: true, confidence: 0.9, responseTimeMs: 2728, escalatedToTicket: false, askedAt: new Date('2026-05-23T21:17:00.000Z') },
  { id: 'Q-0137', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Health insurance for parents?", topic: 'benefits', wasResolved: false, confidence: 0.4, responseTimeMs: 2820, escalatedToTicket: true, ticketId: 'TKT-236', askedAt: new Date('2026-05-23T19:57:00.000Z') },
  { id: 'Q-0140', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "When will salary be credited?", topic: 'payroll', wasResolved: true, confidence: 0.87, responseTimeMs: 1534, escalatedToTicket: false, askedAt: new Date('2026-05-23T19:16:00.000Z') },
  { id: 'Q-0112', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Buddy program details?", topic: 'onboarding', wasResolved: true, confidence: 0.96, responseTimeMs: 1283, escalatedToTicket: false, askedAt: new Date('2026-05-23T18:14:00.000Z') },
  { id: 'Q-0066', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Confluence is read-only for me", topic: 'access', wasResolved: true, confidence: 0.88, responseTimeMs: 3687, escalatedToTicket: false, askedAt: new Date('2026-05-23T18:06:00.000Z') },
  { id: 'Q-0104', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Meeting room display offline", topic: 'meeting', wasResolved: true, confidence: 0.82, responseTimeMs: 3739, escalatedToTicket: false, askedAt: new Date('2026-05-23T17:14:00.000Z') },
  { id: 'Q-0019', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Day 1 checklist for new joiners?", topic: 'onboarding', wasResolved: true, confidence: 0.81, responseTimeMs: 2621, escalatedToTicket: false, askedAt: new Date('2026-05-23T15:25:00.000Z') },
  { id: 'Q-0145', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Where is my payslip for March?", topic: 'payroll', wasResolved: true, confidence: 0.69, responseTimeMs: 1651, escalatedToTicket: false, askedAt: new Date('2026-05-23T14:44:00.000Z') },
  { id: 'Q-0058', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "GitHub access for new repo", topic: 'access', wasResolved: true, confidence: 0.8, responseTimeMs: 1700, escalatedToTicket: false, askedAt: new Date('2026-05-23T14:24:00.000Z') },
  { id: 'Q-0007', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.91, responseTimeMs: 1650, escalatedToTicket: false, askedAt: new Date('2026-05-23T14:04:00.000Z') },
  { id: 'Q-0131', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Cannot access shared drive", topic: 'access', wasResolved: true, confidence: 0.93, responseTimeMs: 2862, escalatedToTicket: false, askedAt: new Date('2026-05-23T11:42:00.000Z') },
  { id: 'Q-0036', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Confluence is read-only for me", topic: 'access', wasResolved: true, confidence: 0.9, responseTimeMs: 3165, escalatedToTicket: false, askedAt: new Date('2026-05-23T11:23:00.000Z') },
  { id: 'Q-0085', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Buddy program details?", topic: 'onboarding', wasResolved: true, confidence: 0.75, responseTimeMs: 3024, escalatedToTicket: false, askedAt: new Date('2026-05-23T10:39:00.000Z') },
  { id: 'Q-0043', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "2FA backup codes lost", topic: 'password', wasResolved: true, confidence: 0.82, responseTimeMs: 1976, escalatedToTicket: false, askedAt: new Date('2026-05-23T10:23:00.000Z') },
  { id: 'Q-0111', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.95, responseTimeMs: 1781, escalatedToTicket: false, askedAt: new Date('2026-05-23T10:17:00.000Z') },
  { id: 'Q-0075', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Where is my payslip for March?", topic: 'payroll', wasResolved: true, confidence: 0.95, responseTimeMs: 1520, escalatedToTicket: false, askedAt: new Date('2026-05-23T09:16:00.000Z') },
  { id: 'Q-0047', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Expense limit for laptop accessories?", topic: 'expense', wasResolved: true, confidence: 0.8, responseTimeMs: 2061, escalatedToTicket: false, askedAt: new Date('2026-05-23T08:36:00.000Z') },
  { id: 'Q-0143', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: true, confidence: 0.8, responseTimeMs: 3334, escalatedToTicket: false, askedAt: new Date('2026-05-23T07:32:00.000Z') },
  { id: 'Q-0032', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Office 365 reactivation", topic: 'software', wasResolved: true, confidence: 0.97, responseTimeMs: 4349, escalatedToTicket: false, askedAt: new Date('2026-05-23T07:02:00.000Z') },
  { id: 'Q-0035', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Carry-forward leave to next year?", topic: 'leave', wasResolved: false, confidence: 0.46, responseTimeMs: 3437, escalatedToTicket: false, askedAt: new Date('2026-05-23T05:53:00.000Z') },
  { id: 'Q-0017', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Can I use VPN from abroad?", topic: 'vpn', wasResolved: false, confidence: 0.57, responseTimeMs: 1083, escalatedToTicket: false, askedAt: new Date('2026-05-23T05:27:00.000Z') },
  { id: 'Q-0150', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: false, confidence: 0.35, responseTimeMs: 2341, escalatedToTicket: true, ticketId: 'TKT-249', askedAt: new Date('2026-05-23T04:37:00.000Z') },
  { id: 'Q-0091', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Laptop screen flickering", topic: 'hardware', wasResolved: false, confidence: 0.45, responseTimeMs: 4419, escalatedToTicket: true, ticketId: 'TKT-190', askedAt: new Date('2026-05-23T02:03:00.000Z') },
  { id: 'Q-0020', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Dental coverage included?", topic: 'benefits', wasResolved: true, confidence: 0.95, responseTimeMs: 1926, escalatedToTicket: false, askedAt: new Date('2026-05-23T01:37:00.000Z') },
  { id: 'Q-0012', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Tax declaration deadline?", topic: 'payroll', wasResolved: true, confidence: 0.89, responseTimeMs: 1396, escalatedToTicket: false, askedAt: new Date('2026-05-23T00:51:00.000Z') },
  { id: 'Q-0057', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Slack notifications not working", topic: 'software', wasResolved: true, confidence: 0.94, responseTimeMs: 1627, escalatedToTicket: false, askedAt: new Date('2026-05-23T00:37:00.000Z') },
  { id: 'Q-0141', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Dress code for client meetings?", topic: 'policy', wasResolved: true, confidence: 0.88, responseTimeMs: 836, escalatedToTicket: false, askedAt: new Date('2026-05-23T00:29:00.000Z') },
  { id: 'Q-0081', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How many leaves do I have left?", topic: 'leave', wasResolved: true, confidence: 0.87, responseTimeMs: 3887, escalatedToTicket: false, askedAt: new Date('2026-05-23T00:00:00.000Z') },
  { id: 'Q-0069', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Can I split my casual leaves?", topic: 'leave', wasResolved: true, confidence: 0.98, responseTimeMs: 2609, escalatedToTicket: false, askedAt: new Date('2026-05-22T23:23:00.000Z') },
  { id: 'Q-0160', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Cannot access shared drive", topic: 'access', wasResolved: true, confidence: 0.8, responseTimeMs: 3661, escalatedToTicket: false, askedAt: new Date('2026-05-22T16:35:00.000Z') },
  { id: 'Q-0063', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Is the office open this Saturday?", topic: 'other', wasResolved: false, confidence: 0.43, responseTimeMs: 2448, escalatedToTicket: false, askedAt: new Date('2026-05-22T15:13:00.000Z') },
  { id: 'Q-0135', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: true, confidence: 0.85, responseTimeMs: 2277, escalatedToTicket: false, askedAt: new Date('2026-05-22T10:56:00.000Z') },
  { id: 'Q-0096', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Visitor parking rules?", topic: 'other', wasResolved: true, confidence: 0.95, responseTimeMs: 3668, escalatedToTicket: false, askedAt: new Date('2026-05-22T10:27:00.000Z') },
  { id: 'Q-0048', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Where is my payslip for March?", topic: 'payroll', wasResolved: true, confidence: 0.95, responseTimeMs: 1737, escalatedToTicket: false, askedAt: new Date('2026-05-22T09:23:00.000Z') },
  { id: 'Q-0004', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Visitor parking rules?", topic: 'other', wasResolved: true, confidence: 0.88, responseTimeMs: 2884, escalatedToTicket: false, askedAt: new Date('2026-05-22T06:00:00.000Z') },
  { id: 'Q-0144', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Cannot find Zoom recording", topic: 'meeting', wasResolved: true, confidence: 0.81, responseTimeMs: 1048, escalatedToTicket: false, askedAt: new Date('2026-05-22T00:17:00.000Z') },
  { id: 'Q-0152', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Cafeteria menu today?", topic: 'other', wasResolved: true, confidence: 0.86, responseTimeMs: 1876, escalatedToTicket: false, askedAt: new Date('2026-05-21T20:33:00.000Z') },
  { id: 'Q-0100', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How do I connect to the office VPN?", topic: 'vpn', wasResolved: false, confidence: 0.65, responseTimeMs: 844, escalatedToTicket: true, ticketId: 'TKT-199', askedAt: new Date('2026-05-21T19:55:00.000Z') },
  { id: 'Q-0107', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Can I use passwordless login?", topic: 'password', wasResolved: false, confidence: 0.46, responseTimeMs: 4272, escalatedToTicket: true, ticketId: 'TKT-206', askedAt: new Date('2026-05-21T18:55:00.000Z') },
  { id: 'Q-0013', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Forgot my SSO password", topic: 'password', wasResolved: false, confidence: 0.48, responseTimeMs: 1100, escalatedToTicket: false, askedAt: new Date('2026-05-21T17:52:00.000Z') },
  { id: 'Q-0008', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Apply leave for next Friday", topic: 'leave', wasResolved: true, confidence: 0.85, responseTimeMs: 3985, escalatedToTicket: false, askedAt: new Date('2026-05-21T15:52:00.000Z') },
  { id: 'Q-0159', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Headphones request", topic: 'hardware', wasResolved: true, confidence: 0.91, responseTimeMs: 3189, escalatedToTicket: false, askedAt: new Date('2026-05-21T11:35:00.000Z') },
  { id: 'Q-0060', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Book the boardroom for Thursday", topic: 'meeting', wasResolved: true, confidence: 0.79, responseTimeMs: 2175, escalatedToTicket: false, askedAt: new Date('2026-05-21T11:24:00.000Z') },
  { id: 'Q-0022', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How do I connect to the office VPN?", topic: 'vpn', wasResolved: false, confidence: 0.35, responseTimeMs: 2932, escalatedToTicket: true, ticketId: 'TKT-121', askedAt: new Date('2026-05-21T10:50:00.000Z') },
  { id: 'Q-0123', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: true, confidence: 0.93, responseTimeMs: 2471, escalatedToTicket: false, askedAt: new Date('2026-05-21T03:33:00.000Z') },
  { id: 'Q-0156', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Can I use passwordless login?", topic: 'password', wasResolved: false, confidence: 0.39, responseTimeMs: 1957, escalatedToTicket: true, ticketId: 'TKT-255', askedAt: new Date('2026-05-21T01:20:00.000Z') },
  { id: 'Q-0041', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Confluence is read-only for me", topic: 'access', wasResolved: true, confidence: 0.72, responseTimeMs: 1920, escalatedToTicket: false, askedAt: new Date('2026-05-20T23:48:00.000Z') },
  { id: 'Q-0106', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Office 365 reactivation", topic: 'software', wasResolved: true, confidence: 0.93, responseTimeMs: 3310, escalatedToTicket: false, askedAt: new Date('2026-05-20T21:05:00.000Z') },
  { id: 'Q-0164', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Where is my payslip for March?", topic: 'payroll', wasResolved: true, confidence: 0.81, responseTimeMs: 3990, escalatedToTicket: false, askedAt: new Date('2026-05-20T19:48:00.000Z') },
  { id: 'Q-0053', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Expense limit for laptop accessories?", topic: 'expense', wasResolved: false, confidence: 0.96, responseTimeMs: 3496, escalatedToTicket: false, askedAt: new Date('2026-05-20T19:10:00.000Z') },
  { id: 'Q-0084', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.84, responseTimeMs: 1431, escalatedToTicket: false, askedAt: new Date('2026-05-20T12:10:00.000Z') },
  { id: 'Q-0103', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Gym reimbursement claim", topic: 'benefits', wasResolved: true, confidence: 0.86, responseTimeMs: 2805, escalatedToTicket: false, askedAt: new Date('2026-05-20T09:30:00.000Z') },
  { id: 'Q-0136', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Tax declaration deadline?", topic: 'payroll', wasResolved: false, confidence: 0.79, responseTimeMs: 1200, escalatedToTicket: false, askedAt: new Date('2026-05-20T05:46:00.000Z') },
  { id: 'Q-0113', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Internal transfer policy?", topic: 'policy', wasResolved: true, confidence: 0.92, responseTimeMs: 3725, escalatedToTicket: false, askedAt: new Date('2026-05-19T23:56:00.000Z') },
  { id: 'Q-0088', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Tax declaration deadline?", topic: 'payroll', wasResolved: true, confidence: 0.73, responseTimeMs: 3734, escalatedToTicket: false, askedAt: new Date('2026-05-19T22:46:00.000Z') },
  { id: 'Q-0115', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.87, responseTimeMs: 2142, escalatedToTicket: false, askedAt: new Date('2026-05-19T19:59:00.000Z') },
  { id: 'Q-0080', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Forgot my SSO password", topic: 'password', wasResolved: true, confidence: 0.7, responseTimeMs: 4428, escalatedToTicket: false, askedAt: new Date('2026-05-19T16:15:00.000Z') },
  { id: 'Q-0056', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use VPN from abroad?", topic: 'vpn', wasResolved: true, confidence: 0.79, responseTimeMs: 2014, escalatedToTicket: false, askedAt: new Date('2026-05-19T14:19:00.000Z') },
  { id: 'Q-0079', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "My expense is stuck in approval", topic: 'expense', wasResolved: true, confidence: 0.91, responseTimeMs: 3306, escalatedToTicket: false, askedAt: new Date('2026-05-19T11:32:00.000Z') },
  { id: 'Q-0089', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Apply leave for next Friday", topic: 'leave', wasResolved: true, confidence: 0.9, responseTimeMs: 2867, escalatedToTicket: false, askedAt: new Date('2026-05-19T04:27:00.000Z') },
  { id: 'Q-0039', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "How to submit travel expenses?", topic: 'expense', wasResolved: false, confidence: 0.92, responseTimeMs: 2489, escalatedToTicket: true, ticketId: 'TKT-138', askedAt: new Date('2026-05-19T00:51:00.000Z') },
  { id: 'Q-0001', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "GitHub access for new repo", topic: 'access', wasResolved: true, confidence: 0.73, responseTimeMs: 1669, escalatedToTicket: false, askedAt: new Date('2026-05-18T21:27:00.000Z') },
  { id: 'Q-0163', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Where is my payslip for March?", topic: 'payroll', wasResolved: true, confidence: 0.79, responseTimeMs: 3630, escalatedToTicket: false, askedAt: new Date('2026-05-18T13:50:00.000Z') },
  { id: 'Q-0127', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "How do I reset my password?", topic: 'password', wasResolved: true, confidence: 0.79, responseTimeMs: 2056, escalatedToTicket: false, askedAt: new Date('2026-05-18T09:50:00.000Z') },
  { id: 'Q-0044', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Day 1 checklist for new joiners?", topic: 'onboarding', wasResolved: true, confidence: 0.89, responseTimeMs: 883, escalatedToTicket: false, askedAt: new Date('2026-05-18T09:23:00.000Z') },
  { id: 'Q-0171', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "GitHub access for new repo", topic: 'access', wasResolved: false, confidence: 0.93, responseTimeMs: 3394, escalatedToTicket: true, ticketId: 'TKT-270', askedAt: new Date('2026-05-18T05:05:00.000Z') },
  { id: 'Q-0138', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "How to set up email on phone?", topic: 'onboarding', wasResolved: false, confidence: 0.45, responseTimeMs: 4008, escalatedToTicket: false, askedAt: new Date('2026-05-18T00:50:00.000Z') },
  { id: 'Q-0122', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Need an external monitor", topic: 'hardware', wasResolved: false, confidence: 0.55, responseTimeMs: 2266, escalatedToTicket: true, ticketId: 'TKT-221', askedAt: new Date('2026-05-17T10:04:00.000Z') },
  { id: 'Q-0026', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: true, confidence: 0.84, responseTimeMs: 1982, escalatedToTicket: false, askedAt: new Date('2026-05-17T04:06:00.000Z') },
  { id: 'Q-0071', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "PF deduction seems wrong", topic: 'payroll', wasResolved: false, confidence: 0.45, responseTimeMs: 2886, escalatedToTicket: false, askedAt: new Date('2026-05-17T02:17:00.000Z') },
  { id: 'Q-0168', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Laptop screen flickering", topic: 'hardware', wasResolved: true, confidence: 0.84, responseTimeMs: 2865, escalatedToTicket: false, askedAt: new Date('2026-05-16T15:26:00.000Z') },
  { id: 'Q-0175', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Laptop screen flickering", topic: 'hardware', wasResolved: true, confidence: 0.88, responseTimeMs: 3247, escalatedToTicket: false, askedAt: new Date('2026-05-16T08:01:00.000Z') },
  { id: 'Q-0031', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Calendar invite to external client", topic: 'meeting', wasResolved: true, confidence: 0.9, responseTimeMs: 3108, escalatedToTicket: false, askedAt: new Date('2026-05-16T07:24:00.000Z') },
  { id: 'Q-0061', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "2FA backup codes lost", topic: 'password', wasResolved: true, confidence: 0.86, responseTimeMs: 873, escalatedToTicket: false, askedAt: new Date('2026-05-15T07:35:00.000Z') },
  { id: 'Q-0121', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Apply leave for next Friday", topic: 'leave', wasResolved: true, confidence: 0.79, responseTimeMs: 3882, escalatedToTicket: false, askedAt: new Date('2026-05-13T21:09:00.000Z') },
  { id: 'Q-0153', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Tax declaration deadline?", topic: 'payroll', wasResolved: true, confidence: 0.74, responseTimeMs: 840, escalatedToTicket: false, askedAt: new Date('2026-05-13T19:43:00.000Z') },
  { id: 'Q-0117', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Health insurance for parents?", topic: 'benefits', wasResolved: false, confidence: 0.56, responseTimeMs: 4267, escalatedToTicket: false, askedAt: new Date('2026-05-13T15:17:00.000Z') },
  { id: 'Q-0014', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Install Figma on my Mac", topic: 'software', wasResolved: true, confidence: 0.81, responseTimeMs: 3803, escalatedToTicket: false, askedAt: new Date('2026-05-13T02:37:00.000Z') },
  { id: 'Q-0120', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "How to submit travel expenses?", topic: 'expense', wasResolved: false, confidence: 0.85, responseTimeMs: 2271, escalatedToTicket: true, ticketId: 'TKT-219', askedAt: new Date('2026-05-13T01:47:00.000Z') },
  { id: 'Q-0161', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Sick leave policy for chronic conditions?", topic: 'leave', wasResolved: false, confidence: 0.6, responseTimeMs: 2341, escalatedToTicket: false, askedAt: new Date('2026-05-12T18:08:00.000Z') },
  { id: 'Q-0059', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Cafeteria menu today?", topic: 'other', wasResolved: false, confidence: 0.62, responseTimeMs: 3899, escalatedToTicket: true, ticketId: 'TKT-158', askedAt: new Date('2026-05-12T15:16:00.000Z') },
  { id: 'Q-0118', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Gym reimbursement claim", topic: 'benefits', wasResolved: true, confidence: 0.81, responseTimeMs: 3477, escalatedToTicket: false, askedAt: new Date('2026-05-11T21:55:00.000Z') },
  { id: 'Q-0146', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Sick leave policy for chronic conditions?", topic: 'leave', wasResolved: true, confidence: 0.78, responseTimeMs: 2926, escalatedToTicket: false, askedAt: new Date('2026-05-11T20:11:00.000Z') },
  { id: 'Q-0037', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Internal transfer policy?", topic: 'policy', wasResolved: true, confidence: 0.92, responseTimeMs: 4435, escalatedToTicket: false, askedAt: new Date('2026-05-11T09:34:00.000Z') },
  { id: 'Q-0133', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "How do I reset my password?", topic: 'password', wasResolved: true, confidence: 0.81, responseTimeMs: 1954, escalatedToTicket: false, askedAt: new Date('2026-05-11T02:04:00.000Z') },
  { id: 'Q-0097', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Dress code for client meetings?", topic: 'policy', wasResolved: true, confidence: 0.97, responseTimeMs: 3743, escalatedToTicket: false, askedAt: new Date('2026-05-10T19:57:00.000Z') },
  { id: 'Q-0046', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "My VPN is super slow today", topic: 'vpn', wasResolved: false, confidence: 0.38, responseTimeMs: 4393, escalatedToTicket: false, askedAt: new Date('2026-05-10T17:01:00.000Z') },
  { id: 'Q-0021', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Recurring meeting setup", topic: 'meeting', wasResolved: false, confidence: 0.86, responseTimeMs: 2959, escalatedToTicket: true, ticketId: 'TKT-120', askedAt: new Date('2026-05-10T02:26:00.000Z') },
  { id: 'Q-0052', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "My expense is stuck in approval", topic: 'expense', wasResolved: true, confidence: 0.94, responseTimeMs: 3304, escalatedToTicket: false, askedAt: new Date('2026-05-09T19:04:00.000Z') },
  { id: 'Q-0148', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "ESOP vesting schedule?", topic: 'benefits', wasResolved: true, confidence: 0.97, responseTimeMs: 2585, escalatedToTicket: false, askedAt: new Date('2026-05-09T12:54:00.000Z') },
  { id: 'Q-0155', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "ESOP vesting schedule?", topic: 'benefits', wasResolved: true, confidence: 0.83, responseTimeMs: 4054, escalatedToTicket: false, askedAt: new Date('2026-05-09T11:44:00.000Z') },
  { id: 'Q-0011', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Dental coverage included?", topic: 'benefits', wasResolved: true, confidence: 0.8, responseTimeMs: 4136, escalatedToTicket: false, askedAt: new Date('2026-05-08T20:51:00.000Z') },
  { id: 'Q-0074', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Mouse not working", topic: 'hardware', wasResolved: false, confidence: 0.51, responseTimeMs: 1315, escalatedToTicket: false, askedAt: new Date('2026-05-08T19:08:00.000Z') },
  { id: 'Q-0045', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.84, responseTimeMs: 2494, escalatedToTicket: false, askedAt: new Date('2026-05-08T15:55:00.000Z') },
  { id: 'Q-0034', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "What is the WFH policy?", topic: 'policy', wasResolved: false, confidence: 0.95, responseTimeMs: 3311, escalatedToTicket: false, askedAt: new Date('2026-05-08T13:34:00.000Z') },
  { id: 'Q-0062', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use VPN from abroad?", topic: 'vpn', wasResolved: true, confidence: 0.86, responseTimeMs: 2709, escalatedToTicket: false, askedAt: new Date('2026-05-08T08:37:00.000Z') },
  { id: 'Q-0078', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "GitHub access for new repo", topic: 'access', wasResolved: true, confidence: 0.95, responseTimeMs: 4494, escalatedToTicket: false, askedAt: new Date('2026-05-08T06:05:00.000Z') },
  { id: 'Q-0070', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Cannot access shared drive", topic: 'access', wasResolved: true, confidence: 0.86, responseTimeMs: 2168, escalatedToTicket: false, askedAt: new Date('2026-05-07T11:56:00.000Z') },
  { id: 'Q-0082', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Bonus payment date?", topic: 'payroll', wasResolved: true, confidence: 0.92, responseTimeMs: 907, escalatedToTicket: false, askedAt: new Date('2026-05-07T05:59:00.000Z') },
  { id: 'Q-0025', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Need Notion access", topic: 'software', wasResolved: true, confidence: 0.85, responseTimeMs: 1721, escalatedToTicket: false, askedAt: new Date('2026-05-06T13:59:00.000Z') },
  { id: 'Q-0172', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Office 365 reactivation", topic: 'software', wasResolved: false, confidence: 0.36, responseTimeMs: 3255, escalatedToTicket: false, askedAt: new Date('2026-05-06T04:47:00.000Z') },
  { id: 'Q-0033', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Sick leave policy for chronic conditions?", topic: 'leave', wasResolved: true, confidence: 0.97, responseTimeMs: 981, escalatedToTicket: false, askedAt: new Date('2026-05-06T02:57:00.000Z') },
  { id: 'Q-0094', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Office 365 reactivation", topic: 'software', wasResolved: false, confidence: 0.49, responseTimeMs: 3103, escalatedToTicket: false, askedAt: new Date('2026-05-03T19:07:00.000Z') },
  { id: 'Q-0076', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "AWS console access request", topic: 'access', wasResolved: true, confidence: 0.89, responseTimeMs: 2097, escalatedToTicket: false, askedAt: new Date('2026-05-03T18:30:00.000Z') },
  { id: 'Q-0003', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Apply leave for next Friday", topic: 'leave', wasResolved: true, confidence: 0.8, responseTimeMs: 3907, escalatedToTicket: false, askedAt: new Date('2026-05-03T08:46:00.000Z') },
  { id: 'Q-0054', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Where is the team offsite happening?", topic: 'other', wasResolved: false, confidence: 0.51, responseTimeMs: 1567, escalatedToTicket: true, ticketId: 'TKT-153', askedAt: new Date('2026-05-03T06:01:00.000Z') },
  { id: 'Q-0132', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: true, confidence: 0.89, responseTimeMs: 2826, escalatedToTicket: false, askedAt: new Date('2026-05-02T16:50:00.000Z') },
  { id: 'Q-0090', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I split my casual leaves?", topic: 'leave', wasResolved: false, confidence: 0.96, responseTimeMs: 4128, escalatedToTicket: true, ticketId: 'TKT-189', askedAt: new Date('2026-05-01T16:36:00.000Z') },
  { id: 'Q-0086', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Apply leave for next Friday", topic: 'leave', wasResolved: true, confidence: 0.72, responseTimeMs: 2934, escalatedToTicket: false, askedAt: new Date('2026-04-30T12:40:00.000Z') },
  { id: 'Q-0129', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Need access to Jira", topic: 'access', wasResolved: true, confidence: 0.95, responseTimeMs: 4280, escalatedToTicket: false, askedAt: new Date('2026-04-30T12:02:00.000Z') },
  { id: 'Q-0139', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Book the boardroom for Thursday", topic: 'meeting', wasResolved: true, confidence: 0.98, responseTimeMs: 2070, escalatedToTicket: false, askedAt: new Date('2026-04-30T10:42:00.000Z') },
  { id: 'Q-0006', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: false, confidence: 0.5, responseTimeMs: 1531, escalatedToTicket: false, askedAt: new Date('2026-04-29T21:02:00.000Z') },
  { id: 'Q-0110', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Need an external monitor", topic: 'hardware', wasResolved: false, confidence: 0.58, responseTimeMs: 2243, escalatedToTicket: false, askedAt: new Date('2026-04-28T20:21:00.000Z') },
  { id: 'Q-0087', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Notice period rules?", topic: 'policy', wasResolved: true, confidence: 0.81, responseTimeMs: 3184, escalatedToTicket: false, askedAt: new Date('2026-04-28T19:13:00.000Z') },
  { id: 'Q-0030', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Forgot my SSO password", topic: 'password', wasResolved: true, confidence: 0.92, responseTimeMs: 1145, escalatedToTicket: false, askedAt: new Date('2026-04-28T08:04:00.000Z') },
  { id: 'Q-0124', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "GitHub access for new repo", topic: 'access', wasResolved: false, confidence: 0.55, responseTimeMs: 2572, escalatedToTicket: true, ticketId: 'TKT-223', askedAt: new Date('2026-04-28T07:06:00.000Z') },
  { id: 'Q-0169', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Cannot find Zoom recording", topic: 'meeting', wasResolved: true, confidence: 0.96, responseTimeMs: 2701, escalatedToTicket: false, askedAt: new Date('2026-04-28T06:44:00.000Z') },
  { id: 'Q-0109', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How many leaves do I have left?", topic: 'leave', wasResolved: true, confidence: 0.88, responseTimeMs: 1092, escalatedToTicket: false, askedAt: new Date('2026-04-27T23:56:00.000Z') },
  { id: 'Q-0147', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Mouse not working", topic: 'hardware', wasResolved: true, confidence: 0.82, responseTimeMs: 2288, escalatedToTicket: false, askedAt: new Date('2026-04-27T10:16:00.000Z') },
  { id: 'Q-0149', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Sick leave policy for chronic conditions?", topic: 'leave', wasResolved: true, confidence: 0.95, responseTimeMs: 1381, escalatedToTicket: false, askedAt: new Date('2026-04-25T09:20:00.000Z') },
  { id: 'Q-0009', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "What is the WFH policy?", topic: 'policy', wasResolved: true, confidence: 0.86, responseTimeMs: 3661, escalatedToTicket: false, askedAt: new Date('2026-04-24T16:23:00.000Z') },
  { id: 'Q-0170', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Office 365 reactivation", topic: 'software', wasResolved: false, confidence: 0.86, responseTimeMs: 1272, escalatedToTicket: true, ticketId: 'TKT-269', askedAt: new Date('2026-04-24T15:19:00.000Z') },
  { id: 'Q-0114', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Internal transfer policy?", topic: 'policy', wasResolved: true, confidence: 0.97, responseTimeMs: 2322, escalatedToTicket: false, askedAt: new Date('2026-04-24T06:54:00.000Z') },
  { id: 'Q-0099', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.7, responseTimeMs: 1905, escalatedToTicket: false, askedAt: new Date('2026-04-24T02:28:00.000Z') },
  { id: 'Q-0173', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: true, confidence: 0.98, responseTimeMs: 2842, escalatedToTicket: false, askedAt: new Date('2026-04-23T13:24:00.000Z') },
  { id: 'Q-0010', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Forgot my SSO password", topic: 'password', wasResolved: false, confidence: 0.61, responseTimeMs: 3954, escalatedToTicket: true, ticketId: 'TKT-109', askedAt: new Date('2026-04-23T13:15:00.000Z') },
  { id: 'Q-0077', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: true, confidence: 0.96, responseTimeMs: 3556, escalatedToTicket: false, askedAt: new Date('2026-04-23T11:05:00.000Z') },
  { id: 'Q-0162', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.94, responseTimeMs: 3458, escalatedToTicket: false, askedAt: new Date('2026-04-23T08:12:00.000Z') },
  { id: 'Q-0167', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Dental coverage included?", topic: 'benefits', wasResolved: true, confidence: 0.86, responseTimeMs: 2019, escalatedToTicket: false, askedAt: new Date('2026-04-23T04:37:00.000Z') },
  { id: 'Q-0142', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Bonus payment date?", topic: 'payroll', wasResolved: true, confidence: 0.75, responseTimeMs: 4170, escalatedToTicket: false, askedAt: new Date('2026-04-22T17:51:00.000Z') },
  { id: 'Q-0015', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Buddy program details?", topic: 'onboarding', wasResolved: true, confidence: 0.98, responseTimeMs: 3650, escalatedToTicket: false, askedAt: new Date('2026-04-22T00:57:00.000Z') },
  { id: 'Q-0125', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Day 1 checklist for new joiners?", topic: 'onboarding', wasResolved: true, confidence: 0.96, responseTimeMs: 1071, escalatedToTicket: false, askedAt: new Date('2026-04-22T00:55:00.000Z') },
  { id: 'Q-0154', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How to set up email on phone?", topic: 'onboarding', wasResolved: true, confidence: 0.88, responseTimeMs: 4184, escalatedToTicket: false, askedAt: new Date('2026-04-21T01:51:00.000Z') },
  { id: 'Q-0018', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How to set up email on phone?", topic: 'onboarding', wasResolved: true, confidence: 0.69, responseTimeMs: 3820, escalatedToTicket: false, askedAt: new Date('2026-04-20T19:52:00.000Z') },
  { id: 'Q-0073', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Replace charger?", topic: 'hardware', wasResolved: true, confidence: 0.94, responseTimeMs: 3991, escalatedToTicket: false, askedAt: new Date('2026-04-19T15:52:00.000Z') },
  { id: 'Q-0028', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.89, responseTimeMs: 1968, escalatedToTicket: false, askedAt: new Date('2026-04-19T00:52:00.000Z') },
  { id: 'Q-0016', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Password reset link expired", topic: 'password', wasResolved: false, confidence: 0.81, responseTimeMs: 1011, escalatedToTicket: false, askedAt: new Date('2026-04-17T17:06:00.000Z') },
  { id: 'Q-0126', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Expense limit for laptop accessories?", topic: 'expense', wasResolved: true, confidence: 0.9, responseTimeMs: 1905, escalatedToTicket: false, askedAt: new Date('2026-04-15T11:22:00.000Z') },
  { id: 'Q-0055', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Why is my VPN dropping?", topic: 'vpn', wasResolved: false, confidence: 0.47, responseTimeMs: 4165, escalatedToTicket: true, ticketId: 'TKT-154', askedAt: new Date('2026-04-14T23:01:00.000Z') },
  { id: 'Q-0098', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "PF deduction seems wrong", topic: 'payroll', wasResolved: true, confidence: 0.89, responseTimeMs: 2768, escalatedToTicket: false, askedAt: new Date('2026-04-12T11:31:00.000Z') },
  { id: 'Q-0051', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Replace charger?", topic: 'hardware', wasResolved: true, confidence: 0.95, responseTimeMs: 1889, escalatedToTicket: false, askedAt: new Date('2026-04-11T21:00:00.000Z') },
  { id: 'Q-0102', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Forgot my SSO password", topic: 'password', wasResolved: true, confidence: 0.97, responseTimeMs: 3173, escalatedToTicket: false, askedAt: new Date('2026-04-10T14:37:00.000Z') },
  { id: 'Q-0092', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "PF deduction seems wrong", topic: 'payroll', wasResolved: true, confidence: 0.81, responseTimeMs: 3843, escalatedToTicket: false, askedAt: new Date('2026-04-10T07:24:00.000Z') },
  { id: 'Q-0101', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Book the boardroom for Thursday", topic: 'meeting', wasResolved: true, confidence: 0.83, responseTimeMs: 2634, escalatedToTicket: false, askedAt: new Date('2026-04-09T18:46:00.000Z') },
  { id: 'Q-0005', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.91, responseTimeMs: 1990, escalatedToTicket: false, askedAt: new Date('2026-04-08T08:26:00.000Z') },
  { id: 'Q-0151', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Confluence is read-only for me", topic: 'access', wasResolved: true, confidence: 0.84, responseTimeMs: 1705, escalatedToTicket: false, askedAt: new Date('2026-04-08T05:41:00.000Z') },
  { id: 'Q-0050', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "AWS console access request", topic: 'access', wasResolved: true, confidence: 0.84, responseTimeMs: 1925, escalatedToTicket: false, askedAt: new Date('2026-04-07T11:57:00.000Z') },
  { id: 'Q-0067', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.95, responseTimeMs: 1716, escalatedToTicket: false, askedAt: new Date('2026-04-07T08:15:00.000Z') },
  { id: 'Q-0049', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Mental health support options?", topic: 'benefits', wasResolved: true, confidence: 0.83, responseTimeMs: 2743, escalatedToTicket: false, askedAt: new Date('2026-04-07T01:09:00.000Z') },
  { id: 'Q-0083', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "When will salary be credited?", topic: 'payroll', wasResolved: true, confidence: 0.85, responseTimeMs: 2970, escalatedToTicket: false, askedAt: new Date('2026-04-05T18:57:00.000Z') },
  { id: 'Q-0038', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Expense limit for laptop accessories?", topic: 'expense', wasResolved: true, confidence: 0.86, responseTimeMs: 3470, escalatedToTicket: false, askedAt: new Date('2026-04-04T11:27:00.000Z') },
  { id: 'Q-0128', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "When will salary be credited?", topic: 'payroll', wasResolved: true, confidence: 0.91, responseTimeMs: 3473, escalatedToTicket: false, askedAt: new Date('2026-04-04T03:32:00.000Z') },
  { id: 'Q-0095', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: true, confidence: 0.86, responseTimeMs: 1395, escalatedToTicket: false, askedAt: new Date('2026-04-03T10:29:00.000Z') },
  { id: 'Q-0024', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Install Figma on my Mac", topic: 'software', wasResolved: true, confidence: 0.82, responseTimeMs: 1832, escalatedToTicket: false, askedAt: new Date('2026-04-03T03:31:00.000Z') },
  { id: 'Q-0040', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "ESOP vesting schedule?", topic: 'benefits', wasResolved: true, confidence: 0.93, responseTimeMs: 3261, escalatedToTicket: false, askedAt: new Date('2026-04-02T00:07:00.000Z') },
  { id: 'Q-0165', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Reimbursement for client dinner", topic: 'expense', wasResolved: true, confidence: 0.68, responseTimeMs: 2794, escalatedToTicket: false, askedAt: new Date('2026-04-01T16:44:00.000Z') },
  { id: 'Q-0023', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Can I use VPN from abroad?", topic: 'vpn', wasResolved: false, confidence: 0.52, responseTimeMs: 2990, escalatedToTicket: false, askedAt: new Date('2026-04-01T11:39:00.000Z') },
  { id: 'Q-0042', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Buddy program details?", topic: 'onboarding', wasResolved: false, confidence: 0.56, responseTimeMs: 2674, escalatedToTicket: false, askedAt: new Date('2026-03-31T18:59:00.000Z') },
  { id: 'Q-0116', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Probation review schedule?", topic: 'onboarding', wasResolved: true, confidence: 0.89, responseTimeMs: 3767, escalatedToTicket: false, askedAt: new Date('2026-03-31T14:19:00.000Z') },
  { id: 'Q-0130', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Notice period rules?", topic: 'policy', wasResolved: true, confidence: 0.82, responseTimeMs: 1448, escalatedToTicket: false, askedAt: new Date('2026-03-31T08:41:00.000Z') },
  { id: 'Q-0158', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Tax declaration deadline?", topic: 'payroll', wasResolved: false, confidence: 0.47, responseTimeMs: 2235, escalatedToTicket: true, ticketId: 'TKT-257', askedAt: new Date('2026-03-31T04:12:00.000Z') },
  { id: 'Q-0027', userId: '1', userEmail: 'admin@vexartech.com', userRole: 'admin', department: 'Management', question: "Reimbursement for client dinner", topic: 'expense', wasResolved: true, confidence: 0.68, responseTimeMs: 1021, escalatedToTicket: false, askedAt: new Date('2026-03-30T15:13:00.000Z') },
  { id: 'Q-0093', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Is the office open this Saturday?", topic: 'other', wasResolved: true, confidence: 0.98, responseTimeMs: 4277, escalatedToTicket: false, askedAt: new Date('2026-03-30T06:57:00.000Z') },
  { id: 'Q-0002', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Where do I get my laptop?", topic: 'onboarding', wasResolved: false, confidence: 0.38, responseTimeMs: 3058, escalatedToTicket: true, ticketId: 'TKT-101', askedAt: new Date('2026-03-30T04:09:00.000Z') },
  { id: 'Q-0068', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "VPN works on phone but not laptop", topic: 'vpn', wasResolved: true, confidence: 0.83, responseTimeMs: 3391, escalatedToTicket: false, askedAt: new Date('2026-03-29T21:57:00.000Z') },
  { id: 'Q-0134', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "How to set up email on phone?", topic: 'onboarding', wasResolved: true, confidence: 0.8, responseTimeMs: 3442, escalatedToTicket: false, askedAt: new Date('2026-03-29T15:24:00.000Z') },
  { id: 'Q-0105', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Replace charger?", topic: 'hardware', wasResolved: false, confidence: 0.86, responseTimeMs: 3075, escalatedToTicket: true, ticketId: 'TKT-204', askedAt: new Date('2026-03-29T04:14:00.000Z') },
  { id: 'Q-0029', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Where do I get my laptop?", topic: 'onboarding', wasResolved: true, confidence: 0.91, responseTimeMs: 3343, escalatedToTicket: false, askedAt: new Date('2026-03-28T13:53:00.000Z') },
  { id: 'Q-0174', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Licence for IntelliJ?", topic: 'software', wasResolved: true, confidence: 0.92, responseTimeMs: 1066, escalatedToTicket: false, askedAt: new Date('2026-03-27T12:02:00.000Z') },
  { id: 'Q-0166', userId: '2', userEmail: 'john.smith@vexartech.com', userRole: 'employee', department: 'IT Support', question: "Can I use passwordless login?", topic: 'password', wasResolved: true, confidence: 0.91, responseTimeMs: 1380, escalatedToTicket: false, askedAt: new Date('2026-03-27T02:25:00.000Z') },
  { id: 'Q-0119', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Probation review schedule?", topic: 'onboarding', wasResolved: true, confidence: 0.93, responseTimeMs: 2736, escalatedToTicket: false, askedAt: new Date('2026-03-26T23:21:00.000Z') },
  { id: 'Q-0065', userId: '3', userEmail: 'sarah.johnson@vexartech.com', userRole: 'employee', department: 'HR', question: "Password reset link expired", topic: 'password', wasResolved: true, confidence: 0.86, responseTimeMs: 2476, escalatedToTicket: false, askedAt: new Date('2026-03-26T02:52:00.000Z') },
]
